on:
  push:
    branches-ignore:
      - master
    paths:
      - 'src/components/**'
      
env:
  CURRENT_BRANCH: "$(basename ${{ github.ref }})"
    
jobs:
  check:
    name: 'check branch on gh-action-exp-2'
    runs-on: ubuntu-latest
    outputs:
      check_output: ${{ steps.check_branch.outputs.sha }}
    steps:
      - name: Get current branch name
        run: echo "Current branch is ${{ env.CURRENT_BRANCH }}"
          
      - name: check branch with the same name on gh-action-exp-2
        id: check_branch
        run: |
            echo "::set-output name=sha::$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/oliver1chen/gh-action-exp-2/branches/gh-action-exp--${{ env.CURRENT_BRANCH }}  | jq -r '.commit.sha')"
            
      - name: chech get sha output
        run: |
            echo "latest release: ${{ steps.check_branch.outputs.sha }}"
    
    
  copy:
    name: 'copy to gh-action-exp-2'
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.check_output != "null" }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Test Step
        run: |
          echo "Check output: ${{ needs.check.outputs.check_output }}"
      
      - name: Get target branch name
        id: get-target-branch-name
        run: |
          branch_name="gh-action-exp--${{ env.CURRENT_BRANCH }}"
          echo "::set-output name=branch_name::$branch_name"

      - name: Pushes gh-action-exp-2
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: 'src/components'
          destination-github-username: 'oliver1chen'
          destination-repository-name: 'gh-action-exp-2'
          target-branch: "${{ steps.get-target-branch-name.outputs.branch_name  }}"
          target-directory: 'src/components/gh-action-exp'
