on:
  push:
    branches-ignore:
      - master
    paths:
      - 'src/components/**'
      
env:
  CURRENT_BRANCH: $(basename ${{ github.ref }})
    
jobs:
  check:
    name: 'check branch on gh-action-exp-2'
    runs-on: ubuntu-latest
    steps:
      - name: Get current branch name
        run: echo "Current branch is ${{ env.CURRENT_BRANCH }}"
          
      - name: check branch with the same name on gh-action-exp-2
        id: check_branch
        run: |
            echo "::set-output name=sha::$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/oliver1chen/gh-action-exp-2/branches/gh-action-exp--${{ env.CURRENT_BRANCH }}  | jq -r '.commit.sha')"
            
      - name: chech get sha output
        run: |
            echo "latest release: ${{ steps.check_branch.outputs.sha }}"
    
    
#   copy:
#     name: 'copy to gh-action-exp-2'
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
      
#       - name: Get current branch name
#         run: echo "Current branch is ${{ env.CURRENT_BRANCH }}"

#       - name: get sha of gh-action-exp-2
#         id: get_sha
#         run: |
#             echo "::set-output name=sha::$(curl -L \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/oliver1chen/gh-action-exp-2/branches/master  | jq -r '.commit.sha')"
            
#       - name: chech get sha output
#         run: |
#             echo "latest release: ${{ steps.get_sha.outputs.sha }}"
            
#       - name: Create new branch in gh-action-exp-2
#         run: |
#             curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/oliver1chen/gh-action-exp-2/git/refs \
#             -d '{"ref":"refs/heads/gh-action-exp--${{ env.CURRENT_BRANCH }}","sha":"${{ steps.get_sha.outputs.sha }}" }'

#       - name: Pushes gh-action-exp-2
#         uses: cpina/github-action-push-to-another-repository@main
#         env:
#           API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
#         with:
#           source-directory: 'src/components'
#           destination-github-username: 'oliver1chen'
#           destination-repository-name: 'gh-action-exp-2'
#           target-branch: 'gh-action-exp--${{ env.CURRENT_BRANCH }}'
#           target-directory: 'src/components/gh-action-exp'


#       - name: Create pull request in gh-action-exp-2
#         run: |
#             curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             https://api.github.com/repos/oliver1chen/gh-action-exp-2/pulls \
#             -d '{"title":"Pull Request from gh-action-exp--${{ env.CURRENT_BRANCH }}","head":"gh-action-exp--${{ env.CURRENT_BRANCH }}","base":"master"}'
