on:
  push:
    branches:
    - master
    
jobs:
  copy:
    name: 'copy to gh-action-exp-2'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate UUID
        id: generate-uuid
        uses: filipstefansson/uuid-action@v1
        
      - name: Check UUID
        run: echo "UUID is ${{ steps.generate-uuid.outputs.uuid }}"
          
#       - name: Create new branch in gh-action-exp-2
#         uses: GuillaumeFalourd/create-other-repo-branch-action@v1.5
#         with:
#           repository_owner: 'oliver1chen'
#           repository_name: 'gh-action-exp-2'
#           new_branch_name: 'gh-action-exp--${{ steps.generate-uuid.outputs.uuid }}'
# #           ssh_deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
#           access_token: ${{ secrets.ACCESS_TOKEN }}
          
#       - name: Create new branch in gh-action-exp-2
#         uses: actions/checkout@v3
#         with:
#           repository: 'oliver1chen/gh-action-exp-2'
#           ref: 'gh-action-exp--${{ steps.generate-uuid.outputs.uuid }}'
# #           path: 'gh-action-exp--${{ steps.generate-uuid.outputs.uuid }}'
# #           ssh-key: ${{ secrets.SSH_DEPLOY_KEY }}
#           token: ${{ secrets.ACCESS_TOKEN }}

      - name: get sha of gh-action-exp-2
        id: get_sha
        run: |
            curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/oliver1chen/gh-action-exp-2/branches/master
            
#       - uses: octokit/request-action@v2.x
#         id: get_sha
#         with:
#           route: GET /repos/{owner}/{repo}/releases/latest
#           owner: oliver1chen
#           repo: gh-action-exp-2
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
            
      - run: "echo latest release: '${{ steps.get_sha.outputs.data }}'"
            
      - name: Create new branch in gh-action-exp-2
        run: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/oliver1chen/gh-action-exp-2/git/refs \
            -d '{"ref":"refs/heads/gh-action-exp--${{ steps.generate-uuid.outputs.uuid }}","sha":"${{ github.sha }}" }'
    
#         uses: octokit/request-action@v2.x
#         id: create_branch
#         env:
#           GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#         with:
#           route: POST /repos/{owner}/{repo}/git/refs
#           owner: oliver1chen
#           repo: gh-action-exp-2
#           ref: "refs/heads/gh-action-exp--${{ steps.generate-uuid.outputs.uuid }}"
#           sha: ${{ github.sha }}
#           mediaType: | # The | is significant!
#             format: raw

      - name: Pushes gh-action-exp-2
        uses: cpina/github-action-push-to-another-repository@main
        env:
#           SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.ACCESS_TOKEN }}
        with:
          source-directory: 'src/components'
          destination-github-username: 'oliver1chen'
          destination-repository-name: 'gh-action-exp-2'
          target-branch: 'gh-action-exp--${{ steps.generate-uuid.outputs.uuid }}'
          target-directory: 'src/components/gh-action-exp'

